apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-filesystem-simple
provisioner:  openshift-storage.cephfs.csi.ceph.com
parameters:
  clusterID: openshift-storage
  fsName: myfs # Name of the filesystem to use.
  pool: myfs-data0
  csi.storage.k8s.io/provisioner-secret-name: rook-ceph-csi
  csi.storage.k8s.io/provisioner-secret-namespace: openshift-storage
  csi.storage.k8s.io/node-stage-secret-name: rook-ceph-csi
  csi.storage.k8s.io/node-stage-secret-namespace: openshift-storage
